### ISSUE TITLE
gevent 1.0rc2 breaks plivo

### ISSUE THREAD

**Issue by trane** [plivo/plivoframework#96]
Testing an inbound call, with TRACE enabled succeeds with the gevent installed through pip.

However, it fails when using the newest gevent based off of libev.

This is using the newest code from the master branch of plivoframework.

```
2013-01-25 12:13:12,516 plivo-outbound[1866]: INFO: OutboundServer started at '127.0.0.1:8084'
2013-01-25 12:13:37,485 plivo-outbound[1866]: INFO: (1) New request from ('127.0.0.1', 52571)
2013-01-25 12:13:37,486 plivo-outbound[1866]: DEBUG: (1) [TRACE] run now
2013-01-25 12:13:37,486 plivo-outbound[1866]: DEBUG: (1) Execute: connect args=''
2013-01-25 12:13:37,486 plivo-outbound[1866]: DEBUG: (1) [TRACE] _protocol_send connect 
2013-01-25 12:13:37,490 plivo-outbound[1866]: DEBUG: (1) [TRACE] _protocol_send connect wait ...
2013-01-25 12:13:37,491 plivo-outbound[1866]: ERROR: (1) Traceback (most recent call last):
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)   File "/usr/local/lib/python2.7/dist-packages/plivo/rest/freeswitch/outboundsocket.py", line 308, in run
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)     self._run()
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)   File "/usr/local/lib/python2.7/dist-packages/plivo/rest/freeswitch/outboundsocket.py", line 318, in _run
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)     self.connect()
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)   File "/usr/local/lib/python2.7/dist-packages/plivo/core/freeswitch/outboundsocket.py", line 54, in connect
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)     connect_response = self._protocol_send("connect")
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)   File "/usr/local/lib/python2.7/dist-packages/plivo/rest/freeswitch/outboundsocket.py", line 140, in _protocol_send
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)     command, args)
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)   File "/usr/local/lib/python2.7/dist-packages/plivo/core/freeswitch/eventsocket.py", line 376, in _protocol_send
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)     _uuid, event = _async_res.get()
2013-01-25 12:13:37,492 plivo-outbound[1866]: ERROR: (1)   File "/usr/local/lib/python2.7/dist-packages/gevent/event.py", line 226, in get
2013-01-25 12:13:37,493 plivo-outbound[1866]: ERROR: (1)     result = self.hub.switch()
2013-01-25 12:13:37,493 plivo-outbound[1866]: ERROR: (1)   File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 330, in switch
2013-01-25 12:13:37,493 plivo-outbound[1866]: ERROR: (1)     switch_out()
2013-01-25 12:13:37,493 plivo-outbound[1866]: ERROR: (1)   File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 334, in switch_out
2013-01-25 12:13:37,493 plivo-outbound[1866]: ERROR: (1)     raise AssertionError('Impossible to call blocking function in the event loop callback')
2013-01-25 12:13:37,493 plivo-outbound[1866]: ERROR: (1) AssertionError: Impossible to call blocking function in the event loop callback
2013-01-25 12:13:37,493 plivo-outbound[1866]: DEBUG: (1) [TRACE] disconnect now
2013-01-25 12:13:37,493 plivo-outbound[1866]: DEBUG: (1) Releasing Connection ...
2013-01-25 12:13:37,493 plivo-outbound[1866]: DEBUG: (1) [TRACE] releasing ...
2013-01-25 12:13:37,493 plivo-outbound[1866]: DEBUG: (1) [TRACE] releasing forced


```

**Comment by AndrewPashkin** [comment]
Fixed it in #132.

**Comment by AndreiPashkin** [comment]
Fixed it in #132
